trigger:
- main  # or your branch

pool:
  vmImage: 'windows-latest'

variables:
  orchestratorTenant: 'default'
  orchestratorFolder: 'Shared'
  robotAccount: 'your_robot_username'
  robotPassword: '$(UiPathPassword)'
  orchestratorUrl: 'https://cloud.uipath.com/YOUR_ACCOUNT'
  releaseName: 'LoginTestAutomation'
  testCase: 'LoginTest_ValidCredentials'

steps:
- task: UiPathInstallPlatform@1
  displayName: 'Install UiPath CLI'

- task: UiPathRunTests@2
  displayName: 'Run UiPath Tests'
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'UiPath-Orchestrator-Connection'
    testSet: 'LoginTestSet'
