# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathTest@5
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Connection of Ui&DevOps'
    disableBuiltInNugetFeeds: true
    testProjectPath: 'https://dev.azure.com/imrantahir0318/UiPath%20Automation/_workitems/edit/130/'
    folderName: 'C:\Users\vmadmin\Documents\UiPath\DevOps test'
    attachRobotLogs: true
    enablePackageMetadata: true